# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AddAlbumForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.albumName = QtWidgets.QLineEdit(self.centralwidget)
        self.albumName.setGeometry(QtCore.QRect(10, 80, 581, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.albumName.setFont(font)
        self.albumName.setText("")
        self.albumName.setAlignment(QtCore.Qt.AlignCenter)
        self.albumName.setClearButtonEnabled(False)
        self.albumName.setObjectName("albumName")
        self.imageUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.imageUrl.setGeometry(QtCore.QRect(10, 130, 581, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.imageUrl.setFont(font)
        self.imageUrl.setText("")
        self.imageUrl.setAlignment(QtCore.Qt.AlignCenter)
        self.imageUrl.setClearButtonEnabled(False)
        self.imageUrl.setObjectName("imageUrl")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(10, 380, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.addPieceButton = QtWidgets.QPushButton(self.centralwidget)
        self.addPieceButton.setGeometry(QtCore.QRect(20, 210, 141, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.addPieceButton.setFont(font)
        self.addPieceButton.setObjectName("addPieceButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(10, 430, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(260, 200, 256, 91))
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Add album"))
        self.albumName.setPlaceholderText(_translate("MainWindow", "Album name"))
        self.imageUrl.setPlaceholderText(_translate("MainWindow", "ImageURL"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.addPieceButton.setText(_translate("MainWindow", "Add to album"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
