# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AddMusicalPiece.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.musicalPieceName = QtWidgets.QLineEdit(self.centralwidget)
        self.musicalPieceName.setGeometry(QtCore.QRect(10, 80, 581, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.musicalPieceName.setFont(font)
        self.musicalPieceName.setText("")
        self.musicalPieceName.setAlignment(QtCore.Qt.AlignCenter)
        self.musicalPieceName.setClearButtonEnabled(False)
        self.musicalPieceName.setObjectName("musicalPieceName")
        self.imageUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.imageUrl.setGeometry(QtCore.QRect(10, 130, 581, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.imageUrl.setFont(font)
        self.imageUrl.setText("")
        self.imageUrl.setAlignment(QtCore.Qt.AlignCenter)
        self.imageUrl.setClearButtonEnabled(False)
        self.imageUrl.setObjectName("imageUrl")
        self.text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(10, 180, 581, 201))
        self.text.setObjectName("text")
        self.groups = QtWidgets.QPushButton(self.centralwidget)
        self.groups.setGeometry(QtCore.QRect(10, 410, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groups.setFont(font)
        self.groups.setObjectName("groups")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(10, 530, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.participants = QtWidgets.QPushButton(self.centralwidget)
        self.participants.setGeometry(QtCore.QRect(10, 470, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.participants.setFont(font)
        self.participants.setObjectName("participants")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Add musical piece"))
        self.musicalPieceName.setPlaceholderText(_translate("MainWindow", "Musical piece name"))
        self.imageUrl.setPlaceholderText(_translate("MainWindow", "ImageURL"))
        self.text.setPlaceholderText(_translate("MainWindow", "Text"))
        self.groups.setText(_translate("MainWindow", "Groups"))
        self.save.setText(_translate("MainWindow", "Save musical piece"))
        self.participants.setText(_translate("MainWindow", "Participants"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
