# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AddReviewForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 431, 131))
        self.textEdit.setObjectName("textEdit")
        self.gradeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.gradeComboBox.setGeometry(QtCore.QRect(240, 230, 91, 22))
        self.gradeComboBox.setObjectName("gradeComboBox")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.gradeComboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 220, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.add_review = QtWidgets.QPushButton(self.centralwidget)
        self.add_review.setGeometry(QtCore.QRect(10, 302, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_review.setFont(font)
        self.add_review.setObjectName("add_review")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Add Review"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Opis"))
        self.gradeComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.gradeComboBox.setItemText(1, _translate("MainWindow", "2"))
        self.gradeComboBox.setItemText(2, _translate("MainWindow", "3"))
        self.gradeComboBox.setItemText(3, _translate("MainWindow", "4"))
        self.gradeComboBox.setItemText(4, _translate("MainWindow", "5"))
        self.gradeComboBox.setItemText(5, _translate("MainWindow", "6"))
        self.gradeComboBox.setItemText(6, _translate("MainWindow", "7"))
        self.gradeComboBox.setItemText(7, _translate("MainWindow", "8"))
        self.gradeComboBox.setItemText(8, _translate("MainWindow", "9"))
        self.gradeComboBox.setItemText(9, _translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "Grade:"))
        self.add_review.setText(_translate("MainWindow", "Add Review"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
