# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\FTN\SIMS\Projekat\SIMSProjekat\UI\CardWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CardWidget(object):
    def setupUi(self, CardWidget):
        CardWidget.setObjectName("CardWidget")
        CardWidget.resize(239, 130)
        CardWidget.setMaximumSize(QtCore.QSize(239, 130))
        self.frame = QtWidgets.QFrame(CardWidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 101, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(CardWidget)
        self.label.setGeometry(QtCore.QRect(120, 16, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(CardWidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 90, 51, 28))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(CardWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 90, 51, 28))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(CardWidget)
        QtCore.QMetaObject.connectSlotsByName(CardWidget)

    def retranslateUi(self, CardWidget):
        _translate = QtCore.QCoreApplication.translate
        CardWidget.setWindowTitle(_translate("CardWidget", "Form"))
        self.label.setText(_translate("CardWidget", "Firstword Second Third Fourth"))
        self.pushButton.setText(_translate("CardWidget", "More"))
        self.pushButton_2.setText(_translate("CardWidget", "Review"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CardWidget = QtWidgets.QWidget()
    ui = Ui_CardWidget()
    ui.setupUi(CardWidget)
    CardWidget.show()
    sys.exit(app.exec_())
