# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ListOfFavourites.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(839, 577)
        self.favourite_label = QtWidgets.QLabel(Dialog)
        self.favourite_label.setGeometry(QtCore.QRect(10, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.favourite_label.setFont(font)
        self.favourite_label.setAlignment(QtCore.Qt.AlignCenter)
        self.favourite_label.setObjectName("favourite_label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 20, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 70, 811, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.favourite_label_2 = QtWidgets.QLabel(Dialog)
        self.favourite_label_2.setGeometry(QtCore.QRect(20, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.favourite_label_2.setFont(font)
        self.favourite_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.favourite_label_2.setObjectName("favourite_label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(440, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.artist_scrollArea = QtWidgets.QScrollArea(Dialog)
        self.artist_scrollArea.setGeometry(QtCore.QRect(20, 130, 781, 341))
        self.artist_scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.artist_scrollArea.setWidgetResizable(True)
        self.artist_scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.artist_scrollArea.setObjectName("artist_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 779, 339))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.artist_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.artist_widget.setGeometry(QtCore.QRect(0, 0, 791, 341))
        self.artist_widget.setObjectName("artist_widget")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.artist_widget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 801, 341))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.artist_layout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.artist_layout_2.setContentsMargins(0, 0, 0, 0)
        self.artist_layout_2.setObjectName("artist_layout_2")
        self.artist_scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.favourite_label.setText(_translate("Dialog", "List name:"))
        self.favourite_label_2.setText(_translate("Dialog", "Choose song to add"))
        self.pushButton.setText(_translate("Dialog", "Make list"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
