# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/WidgetForList.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetForList(object):
    def setupUi(self, WidgetForList):
        WidgetForList.setObjectName("WidgetForList")
        WidgetForList.resize(290, 130)
        WidgetForList.setMaximumSize(QtCore.QSize(290, 130))
        self.frame = QtWidgets.QFrame(WidgetForList)
        self.frame.setGeometry(QtCore.QRect(20, 20, 101, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(WidgetForList)
        self.label.setGeometry(QtCore.QRect(140, 10, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(WidgetForList)
        self.pushButton.setGeometry(QtCore.QRect(150, 80, 101, 28))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(WidgetForList)
        QtCore.QMetaObject.connectSlotsByName(WidgetForList)

    def retranslateUi(self, WidgetForList):
        _translate = QtCore.QCoreApplication.translate
        WidgetForList.setWindowTitle(_translate("WidgetForList", "Form"))
        self.label.setText(_translate("WidgetForList", "Firstword Second Third Fourth"))
        self.pushButton.setText(_translate("WidgetForList", "Add to list"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetForList = QtWidgets.QWidget()
    ui = Ui_WidgetForList()
    ui.setupUi(WidgetForList)
    WidgetForList.show()
    sys.exit(app.exec_())
