from Model.Repository.ConcertRepository import ConcertRepository
from Model.Models.Izvodjenje import Izvodjenje
from Model.DTO.ConcertDTO import ConcertDTO
from Model.Models.Enumerations import VrstaIzvodjenja

class ConcertController():
    def __init__(self, musical_piece_controller) -> None:
        self.concert_repository = ConcertRepository(musical_piece_controller)
        self.musical_piece_controller = musical_piece_controller
    
    def add_concert(self, concert_dto: ConcertDTO):
        muzicka_dela_ids = [md.id for md in concert_dto.muzicka_dela]
        new_concert = Izvodjenje(
            0,  # ID will be generated by the repository
            concert_dto.naziv,
            concert_dto.slika,
            concert_dto.pregledi,
            concert_dto.broj_ocena,
            concert_dto.zbir_ocena,
            concert_dto.mesto,
            concert_dto.vreme,
            concert_dto.link,
            concert_dto.vrsta_izvodjenja,
            [self.musical_piece_controller.get_by_id(md_id) for md_id in muzicka_dela_ids]
        )
        added_concert = self.concert_repository.add_concert(new_concert)
        return added_concert
    
    def load(self):
        return self.concert_repository.load()
    
    def delete_concert(self, naziv: str):
        return self.concert_repository.delete_concert(naziv)
    
    def convert_DTO_to_model(self, concert_dto):
        if isinstance(concert_dto, ConcertDTO):
            muzicka_dela = [self.musical_piece_controller.get_by_id(md.id) for md in concert_dto.muzicka_dela]
            return Izvodjenje(
                concert_dto.id,
                concert_dto.naziv,
                concert_dto.slika,
                concert_dto.pregledi,
                concert_dto.broj_ocena,
                concert_dto.zbir_ocena,
                concert_dto.mesto,
                concert_dto.vreme,
                concert_dto.link,
                concert_dto.vrsta_izvodjenja,
                muzicka_dela
            )
    
    def get_all_concerts(self):
        return self.concert_repository.get_all_concerts()

    def get_by_naziv(self, naziv: str):
        return self.concert_repository.get_by_naziv(naziv)
